### ISSUE TITLE
CI failing on macOS ARM release builds

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/libE57Format#289]
The CI image was recently updated to use macOS 14 on ARM by default.

This is causing CI to fail on macOS release builds (debug build is fine).

```
AddressSanitizer:DEADLYSIGNAL
[----------] 5 tests from SimpleDataHeader
=================================================================
==6381==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001a8996ac0 bp 0x00016f3c3460 sp 0x00016f3c3410 T0)
==6381==The signal is caused by a READ memory access.
==6381==Hint: address points to the zero page.
[ RUN      ] SimpleDataHeader.InvalidPointRangeNodeType
    #0 0x1a8996ac0 in libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*, bool)+0x30 (libunwind.dylib:arm64e+0x5ac0)
    #1 0x1a899896c in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step(bool)+0x220 (libunwind.dylib:arm64e+0x796c)
    #2 0x1a899acd4 in _Unwind_RaiseException+0x1c4 (libunwind.dylib:arm64e+0x9cd4)
    #3 0x19bd18280 in __cxa_throw+0x128 (libc++abi.dylib:arm64e+0x17280)
    #4 0x100c32564 in e57::_validateData3D(e57::Data3D const&)+0x1dc (testE57:arm64+0x1001fa564)
    #5 0x100c32730 in e57::Data3DPointsData_t<float>::Data3DPointsData_t(e57::Data3D&)+0x70 (testE57:arm64+0x1001fa730)
```

This looks like an issue with googletest not handling the exception properly? The test is supposed to throw an exception, and googletest is supposed to check it using `ASSERT_THROW`.

I don't have an ARM Mac to test/debug on, but the first thing to try is to update googletest.

**Edit:** Updated googletest and it still fails.

**Comment by asmaloney** [comment]
This seems to have been fixed by the CI image somewhere along the way.

No idea.
